// <auto-generated />
using CoffeeShop.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeShop.DAL.Migrations
{
    [DbContext(typeof(CoffeeShopContext))]
    partial class CoffeeShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CoffeeEntityCoffeePackEntity", b =>
                {
                    b.Property<int>("CoffeePacksId")
                        .HasColumnType("int");

                    b.Property<int>("CoffeesId")
                        .HasColumnType("int");

                    b.HasKey("CoffeePacksId", "CoffeesId");

                    b.HasIndex(new[] { "CoffeesId" }, "IX_CoffeeEntityCoffeePackEntity_CoffeesId");

                    b.ToTable("CoffeeEntityCoffeePackEntity", (string)null);
                });

            modelBuilder.Entity("CoffeeShop.DAL.Entities.CoffeeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .IsFixedLength();

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.ToTable("Coffee", (string)null);
                });

            modelBuilder.Entity("CoffeeShop.DAL.Entities.CoffeePackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .IsFixedLength();

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.ToTable("CoffeePack", (string)null);
                });

            modelBuilder.Entity("CoffeeEntityCoffeePackEntity", b =>
                {
                    b.HasOne("CoffeeShop.DAL.Entities.CoffeePackEntity", null)
                        .WithMany()
                        .HasForeignKey("CoffeePacksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeShop.DAL.Entities.CoffeeEntity", null)
                        .WithMany()
                        .HasForeignKey("CoffeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
